version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    restart: always
    environment:
      - RABBITMQ_VHOST=aprs
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-tier
  aprs_slurp:
    restart: always
    depends_on:
      - 'rabbitmq'
    image: 'aprsme/aprs_slurp:latest'
    environment:
      - APRS_USERNAME=W5ISP-13
      - APRS_SERVER=g.vntx.net:10152
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=aprs
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-tier

